name: "ensure-conventional-commits"
description: "checks that the commits in a pull request follow conventional commits"
inputs:
  settings-file:
    description: "json files with the settings to be used in the commits validations"
    required: false

runs:
  using: "composite"
  steps:
    - name: 'Validate Commits Provided'
      env:
        SETTINGS_FILE: ${{ inputs.settings-file }}
      run: |
        node ${{ github.action_path }}/main.js
      shell: bash
